In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json

In [14]:
# Testing with 1 page of albums, extracting music data from MusicBoard
url = f"https://api.musicboard.app/v2/albums/popular/?limit=24&offset=216"
ratings_count = []
album_name = []
artist = []
offset = 0
response = requests.get(url)
results = json.loads(response.text)
for entry in results['results']:
    if entry['ratings_count'] > 2500:
        ratings_count.append(entry['ratings_count'])
        album_name.append(entry['title'])
        artist.append(entry['artist']['name'])

df = pd.DataFrame({'Album': album_name,
                   'Artist': artist,
                   'Ratings Count': ratings_count
                  })
df.to_csv('album_list.csv', index=False)

display(df)

                                     Album             Artist  Ratings Count
0                                     Post              Björk           6987
1                               Planet Her           Doja Cat           6971
2                                    Tidal        Fiona Apple           6936
3                  1989 (Taylor's Version)       Taylor Swift           6900
4                                 Scorpion              Drake           6874
5                                    Views              Drake           6836
6          Tranquility Base Hotel & Casino     Arctic Monkeys           6772
7          LONG.LIVE.A$AP (Deluxe Version)         A$AP Rocky           6769
8                             Room On Fire        The Strokes           6756
9                                Stankonia            OutKast           6708
10                              White Pony           Deftones           6699
11                      WE DON'T TRUST YOU             Future           6698
12                                  Humbug     Arctic Monkeys           6687
13                               Let It Be        The Beatles           6607
14                       Depression Cherry        Beach House           6596
15  The Land Is Inhospitable and So Are We             Mitski           6565
16                             This Is Why           Paramore           6508
17                               Doolittle             Pixies           6471
18                   For Emma, Forever Ago           Bon Iver           6463
19                               Homogenic              Björk           6454
20                              VULTURES 2                 ¥$           6454
21                       Electric Ladyland       Jimi Hendrix           6450
22                        For All The Dogs              Drake           6448
23         Desire, I Want To Turn Into You  Caroline Polachek           6446

In [16]:
# Getting album names of albums with 2500+ ratings 
url = f"https://api.musicboard.app/v2/albums/popular/"
ratings_count = []
album_name = []
artist = []
offset = 0
response = requests.get(url)
results = json.loads(response.text)
while (offset < 5000):
    for entry in results['results']:
        if entry['ratings_count'] > 2500:
            ratings_count.append(entry['ratings_count'])
            album_name.append(entry['title'])
            artist.append(entry['artist']['name'])
    offset += 24
    print(offset)
    if results['next']:
        response = requests.get(results['next'])
        results = json.loads(response.text)
    else:
        break

df = pd.DataFrame({'Album': album_name,
                   'Artist': artist,
                   'Ratings Count': ratings_count
                  })
df.to_csv('album_list.csv', index=False)

display(df)

24
48
72
96
120
144
168
192
216
240
264
288
312
336
360
384
408
432
456
480
504
528
552
576
600
624
648
672
696
720
744
768
792
816
840
864
888
912
936
960
984
1008
1032
1056
1080
1104
1128
1152
1176
1200
1224
1248
1272
1296
1320
1344
1368
1392
1416
1440
1464
1488
1512
1536
1560
1584
1608
1632
1656
1680
1704
1728
1752
1776
1800
1824
1848
1872
1896
1920
1944
1968
1992
2016
2040
2064
2088
2112
2136
2160
2184
2208
2232
2256
2280
2304
2328
2352
2376
2400
2424
2448
2472
2496
2520
2544
2568
2592
2616
2640
2664
2688
2712
2736
2760
2784
2808
2832
2856
2880
2904
2928
2952
2976
3000
3024
3048
3072
3096
3120
3144
3168
3192
3216
3240
3264
3288
3312
3336
3360
3384
3408
3432
3456
3480
3504
3528
3552
3576
3600
3624
3648
3672
3696
3720
3744
3768
3792
3816
3840
3864
3888
3912
3936
3960
3984
4008
4032
4056
4080
4104
4128
4152
4176
4200
4224
4248
4272
4296
4320
4344
4368
4392
4416
4440
4464
4488
4512
4536
4560
4584
4608
4632
4656
4680
4704
4728
4752
4776
4800
4824
4848
4872
4896
4920
4944
4968
4992
5016

                                 Album              Artist  Ratings Count
0                                 IGOR  Tyler, The Creator          68335
1                               Blonde         Frank Ocean          65475
2                  To Pimp a Butterfly      Kendrick Lamar          54542
3    My Beautiful Dark Twisted Fantasy          Kanye West          48728
4                          OK Computer           Radiohead          46132
..                                 ...                 ...            ...
626                           Recovery              Eminem           2514
627                             INSANO            Kid Cudi           2513
628     The Piper at the Gates of Dawn          Pink Floyd           2512
629                           Parklife                Blur           2506
630       Born Sinner (Deluxe Version)             J. Cole           2502

[631 rows x 3 columns]

In [17]:
df.head(5)

                               Album              Artist  Ratings Count
0                               IGOR  Tyler, The Creator          68335
1                             Blonde         Frank Ocean          65475
2                To Pimp a Butterfly      Kendrick Lamar          54542
3  My Beautiful Dark Twisted Fantasy          Kanye West          48728
4                        OK Computer           Radiohead          46132

In [18]:
df.isnull().sum()

Album            0
Artist           0
Ratings Count    0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.shape

(631, 3)

In [21]:
new_df = df[['Album','Artist']]
new_df

                                 Album              Artist
0                                 IGOR  Tyler, The Creator
1                               Blonde         Frank Ocean
2                  To Pimp a Butterfly      Kendrick Lamar
3    My Beautiful Dark Twisted Fantasy          Kanye West
4                          OK Computer           Radiohead
..                                 ...                 ...
626                           Recovery              Eminem
627                             INSANO            Kid Cudi
628     The Piper at the Gates of Dawn          Pink Floyd
629                           Parklife                Blur
630       Born Sinner (Deluxe Version)             J. Cole

[631 rows x 2 columns]

In [22]:
new_df['Album']=new_df['Album'].apply(lambda x:x.lower())
new_df['Artist']=new_df['Artist'].apply(lambda x:x.lower())
new_df

C:\Users\korup\AppData\Local\Temp\ipykernel_19844\607596820.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Album']=new_df['Album'].apply(lambda x:x.lower())
C:\Users\korup\AppData\Local\Temp\ipykernel_19844\607596820.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Artist']=new_df['Artist'].apply(lambda x:x.lower())

                                 Album              Artist
0                                 igor  tyler, the creator
1                               blonde         frank ocean
2                  to pimp a butterfly      kendrick lamar
3    my beautiful dark twisted fantasy          kanye west
4                          ok computer           radiohead
..                                 ...                 ...
626                           recovery              eminem
627                             insano            kid cudi
628     the piper at the gates of dawn          pink floyd
629                           parklife                blur
630       born sinner (deluxe version)             j. cole

[631 rows x 2 columns]

In [23]:
#Formatted to go into url slug api point
new_df['Album'] = new_df['Album'].str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)
new_df['Album'] = new_df['Album'].str.replace(r"\s+", "-", regex=True)
new_df['Artist'] = new_df['Artist'].str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)
new_df['Artist'] = new_df['Artist'].str.replace(r"\s+", "-", regex=True)
new_df

C:\Users\korup\AppData\Local\Temp\ipykernel_19844\608202650.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Album'] = new_df['Album'].str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)
C:\Users\korup\AppData\Local\Temp\ipykernel_19844\608202650.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Album'] = new_df['Album'].str.replace(r"\s+", "-", regex=True)
C:\Users\korup\AppData\Local\Temp\ipykernel_19844\608202650.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Artist'] = new_df['Artist'].str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)
C:\Users\korup\AppData\Local\Temp\ipykernel_19844\608202650.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Artist'] = new_df['Artist'].str.replace(r"\s+", "-", regex=True)

                                 Album             Artist
0                                 igor  tyler-the-creator
1                               blonde        frank-ocean
2                  to-pimp-a-butterfly     kendrick-lamar
3    my-beautiful-dark-twisted-fantasy         kanye-west
4                          ok-computer          radiohead
..                                 ...                ...
626                           recovery             eminem
627                             insano           kid-cudi
628     the-piper-at-the-gates-of-dawn         pink-floyd
629                           parklife               blur
630         born-sinner-deluxe-version             j-cole

[631 rows x 2 columns]

In [24]:
len(new_df.index)

631

In [31]:
test_df = new_df.head(50)
test_df

                                     Album             Artist
0                                     igor  tyler-the-creator
1                                   blonde        frank-ocean
2                      to-pimp-a-butterfly     kendrick-lamar
3        my-beautiful-dark-twisted-fantasy         kanye-west
4                              ok-computer          radiohead
5                                     damn     kendrick-lamar
6                              in-rainbows          radiohead
7                                melodrama              lorde
8                the-dark-side-of-the-moon         pink-floyd
9                  norman-fucking-rockwell       lana-del-rey
10                                folklore       taylor-swift
11                                    sour     olivia-rodrigo
12                              graduation         kanye-west
13                                  yeezus         kanye-west
14                              flower-boy  tyler-the-creator
15                       the-life-of-pablo         kanye-west
16                          channel-orange        frank-ocean
17                               nevermind            nirvana
18                     the-college-dropout         kanye-west
19              mr-morale-the-big-steppers     kendrick-lamar
20                              reputation       taylor-swift
21                                      ye         kanye-west
22                                      am     arctic-monkeys
23                                punisher    phoebe-bridgers
24                 call-me-if-you-get-lost  tyler-the-creator
25               good-kid-maad-city-deluxe     kendrick-lamar
26                             madvillainy         madvillain
27                         kids-see-ghosts    kids-see-ghosts
28                                currents        tame-impala
29                             after-hours         the-weeknd
30                               the-bends          radiohead
31                              astroworld       travis-scott
32                              abbey-road        the-beatles
33                               fine-line       harry-styles
34                                   lover       taylor-swift
35                                    brat         charli-xcx
36                         808s-heartbreak         kanye-west
37                                   kid-a          radiohead
38  when-we-all-fall-asleep-where-do-we-go      billie-eilish
39                                    ctrl                sza
40                       late-registration         kanye-west
41                    hit-me-hard-and-soft      billie-eilish
42                                   donda         kanye-west
43                      wish-you-were-here         pink-floyd
44                        future-nostalgia           dua-lipa
45                       the-queen-is-dead         the-smiths
46                                  utopia       travis-scott
47                                   grace       jeff-buckley
48                    ultraviolence-deluxe       lana-del-rey
49                                 rumours      fleetwood-mac

In [49]:
#Getting the album names, average rating, genre, and artist name for all the albums we collected that had 2500+ ratings
ratings_count = []
album_name = []
artist_name = []
average_album_rating = []
artist_rating = []
artist_rating_count = []
genre = []
# test_df = new_df.head(5)
for index, row in new_df.iterrows():
    album = row['Album']  
    artist = row['Artist']
    url = f"https://api.musicboard.app/v2/albums/from_url_slug/?url_slug=/album/{album}/{artist}/"
    try:
        response = requests.get(url)
        results = json.loads(response.text)
        ratings_count.append(results['ratings_count'])
        album_name.append(results['title'])
        artist_name.append(results['artist']['name'])
        average_album_rating.append(results['average_rating'])
        artist_rating.append(results['artist']['average_rating'])
        artist_rating_count.append(results['artist']['ratings_count'])
        list = []
        for item in results['genres']:
            list.append(item['name'])
        str = ', '.join(list)
        genre.append(str)
    except requests.exceptions.RequestException as e:
        print(f"Error fetching data for Album: {row['Album']} by Artist: {row['Artist']} - {e}")
    except KeyError as e:
        print(f"Missing data in response for Album: {row['Album']} by Artist: {row['Artist']} - {e}")

ratings_df = pd.DataFrame({'album': album_name,
                        'artist': artist_name,
                        'average album rating': average_album_rating,
                        'album ratings count': ratings_count,
                        'artist rating': artist_rating,
                        'artist rating count': artist_rating_count,
                        'genres': genre,
                    })
ratings_df.to_csv('ratings_data.csv', index = False)
display(ratings_df)

Missing data in response for Album: good-kid-maad-city-deluxe by Artist: kendrick-lamar - 'ratings_count'
Missing data in response for Album: mmfood by Artist: mf-doom - 'ratings_count'
Missing data in response for Album: red-taylors-version by Artist: taylor-swift - 'ratings_count'
Missing data in response for Album: did-you-know-that-theres-a-tunnel-under-ocean-blvd by Artist: lana-del-rey - 'ratings_count'
Missing data in response for Album: good-kid-maad-city by Artist: kendrick-lamar - 'ratings_count'
Missing data in response for Album: sgt-peppers-lonely-hearts-club-band by Artist: the-beatles - 'ratings_count'
Missing data in response for Album: renaissance by Artist: beyonc - 'ratings_count'
Missing data in response for Album: lemonade by Artist: beyonc - 'ratings_count'
Missing data in response for Album: whatever-people-say-i-am-thats-what-im-not by Artist: arctic-monkeys - 'ratings_count'
Missing data in response for Album: fearless-taylors-version by Artist: taylor-swift - 'ratings_count'
Missing data in response for Album: section80 by Artist: kendrick-lamar - 'ratings_count'
Missing data in response for Album: motomami by Artist: rosala - 'ratings_count'
Missing data in response for Album: watch-the-throne-deluxe by Artist: jayz - 'ratings_count'
Missing data in response for Album: how-im-feeling-now by Artist: charli-xcx - 'ratings_count'
Missing data in response for Album: enter-the-wutang-36-chambers-expanded-edition by Artist: wutang-clan - 'ratings_count'
Missing data in response for Album: speak-now-taylors-version by Artist: taylor-swift - 'ratings_count'
Missing data in response for Album: whats-going-on by Artist: marvin-gaye - 'ratings_count'
Missing data in response for Album: unknown-pleasures-collectors-edition by Artist: joy-division - 'ratings_count'
Missing data in response for Album: atlonglastaap by Artist: aap-rocky - 'ratings_count'
Missing data in response for Album: eitheror by Artist: elliott-smith - 'ratings_count'
Missing data in response for Album: if-youre-reading-this-its-too-late by Artist: drake - 'ratings_count'
Missing data in response for Album: the-offseason by Artist: j-cole - 'ratings_count'
Missing data in response for Album: cowboy-carter by Artist: beyonc - 'ratings_count'
Missing data in response for Album: 444 by Artist: jayz - 'ratings_count'
Missing data in response for Album: vespertine by Artist: bjrk - 'ratings_count'
Missing data in response for Album: testing by Artist: aap-rocky - 'ratings_count'
Missing data in response for Album: piata by Artist: freddie-gibbs-madlib - 'ratings_count'
Missing data in response for Album: post by Artist: bjrk - 'ratings_count'
Missing data in response for Album: 1989-taylors-version by Artist: taylor-swift - 'ratings_count'
Missing data in response for Album: longliveaap-deluxe-version by Artist: aap-rocky - 'ratings_count'
Missing data in response for Album: we-dont-trust-you by Artist: future - 'ratings_count'
Missing data in response for Album: homogenic by Artist: bjrk - 'ratings_count'
Missing data in response for Album: vultures-2 by Artist:  - 'ratings_count'
Missing data in response for Album: liveloveaap by Artist: aap-rocky - 'ratings_count'
Missing data in response for Album: ready-to-die-the-remaster by Artist: the-notorious-big - 'ratings_count'
Missing data in response for Album: debut by Artist: bjrk - 'ratings_count'
Missing data in response for Album: a-hard-days-night by Artist: the-beatles - 'ratings_count'
Missing data in response for Album:  by Artist: xxxtentacion - 'ratings_count'
Missing data in response for Album: whats-the-story-morning-glory by Artist: oasis - 'ratings_count'
Missing data in response for Album: selected-ambient-works-8592 by Artist: aphex-twin - 'ratings_count'
Missing data in response for Album: orqudeas by Artist: kali-uchis - 'ratings_count'
Missing data in response for Album: el-mal-querer by Artist: rosala - 'ratings_count'
Missing data in response for Album: its-almost-dry by Artist: pusha-t - 'ratings_count'
Missing data in response for Album: metro-boomin-presents-spiderman-across-the-spiderverse-soundtrack-from-and-inspired-by-the-motion-picture by Artist: metro-boomin - 'ratings_count'
Missing data in response for Album: oil-of-every-pearls-uninsides by Artist: sophie - 'ratings_count'
Missing data in response for Album: k12 by Artist: melanie-martinez - 'ratings_count'
Missing data in response for Album: doowops-hooligans by Artist: bruno-mars - 'ratings_count'
Missing data in response for Album: 31520 by Artist: childish-gambino - 'ratings_count'
Missing data in response for Album: straight-outta-compton by Artist: nwa - 'ratings_count'
Missing data in response for Album: the-idler-wheel-is-wiser-than-the-driver-of-the-screw-and-whipping-cords-will-serve-you-more-than-ropes-will-ever-do-expanded-edition by Artist: fiona-apple - 'ratings_count'
Missing data in response for Album: allamerikkkan-bada by Artist: joey-bada - 'ratings_count'
Missing data in response for Album: whats-your-pleasure by Artist: jessie-ware - 'ratings_count'
Missing data in response for Album: we-still-dont-trust-you by Artist: future - 'ratings_count'
Missing data in response for Album: hollywoods-bleeding by Artist: post-malone - 'ratings_count'
Missing data in response for Album: i-dont-like-shit-i-dont-go-outside-an-album-by-earl-sweatshirt by Artist: earl-sweatshirt - 'ratings_count'
Missing data in response for Album: the-death-of-slim-shady-coup-de-grce by Artist: eminem - 'ratings_count'
Missing data in response for Album: good-am by Artist: mac-miller - 'ratings_count'
Missing data in response for Album: a-fever-you-cant-sweat-out by Artist: panic-at-the-disco - 'ratings_count'
Missing data in response for Album: liquid-swords by Artist: geniusgza - 'ratings_count'
Missing data in response for Album: beyonc-platinum-edition by Artist: beyonc - 'ratings_count'
Missing data in response for Album: romance by Artist: fontaines-dc - 'ratings_count'
Missing data in response for Album: sin-miedo-del-amor-y-otros-demonios- by Artist: kali-uchis - 'ratings_count'
Missing data in response for Album: enema-of-the-state by Artist: blink182 - 'ratings_count'
Missing data in response for Album: the-blueprint by Artist: jayz - 'ratings_count'
Missing data in response for Album: overly-dedicated by Artist: kendrick-lamar - 'ratings_count'
Missing data in response for Album: mamas-gun by Artist: erykah-badu - 'ratings_count'
Missing data in response for Album: back-in-black by Artist: acdc - 'ratings_count'
Missing data in response for Album: deathmetal by Artist: panchiko - 'ratings_count'
Missing data in response for Album: speakerboxxxthe-love-below by Artist: outkast - 'ratings_count'
Missing data in response for Album: dirty-computer by Artist: janelle-mone - 'ratings_count'
Missing data in response for Album: emails-i-cant-send by Artist: sabrina-carpenter - 'ratings_count'
Missing data in response for Album: 1989-taylors-version-deluxe by Artist: taylor-swift - 'ratings_count'
Missing data in response for Album: submarine by Artist: the-maras - 'ratings_count'
Missing data in response for Album: voodoo by Artist: dangelo - 'ratings_count'
Missing data in response for Album: cxoxo by Artist: camila-cabello - 'ratings_count'

,album,artist,average album rating,album ratings count,artist rating,artist rating count,genres
0,IGOR,"Tyler, The Creator",8.951645,68348,9.083081,3635,"Pop, Rap/Hip Hop, Jazz, Soul/Funk"
1,Blonde,Frank Ocean,9.126779,65484,9.315145,3592,"Pop, Alternative, R&B"
2,To Pimp a Butterfly,Kendrick Lamar,9.437709,54550,9.490310,5521,"Rap/Hip Hop, Jazz, Soul/Funk"
3,My Beautiful Dark Twisted Fantasy,Kanye West,8.973900,48736,9.003903,5893,Rap/Hip Hop
4,OK Computer,Radiohead,9.097271,46139,9.341484,3558,"Alternative, Rock, Electronic"
...,...,...,...,...,...,...,...
551,Recovery,Eminem,6.040573,2514,7.748666,1687,Rap/Hip Hop
552,INSANO,Kid Cudi,4.961401,2513,8.457998,869,Rap/Hip Hop
553,The Piper at the Gates of Dawn,Pink Floyd,7.410430,2512,9.417789,2451,Rock
554,Parklife,Blur,8.072597,2507,8.877400,677,Rock
555,Born Sinner (Deluxe Version),J. Cole,7.130296,2502,8.154448,1023,Rap/Hip Hop